---
title: "Data Manipulation"
author: "Xiaoyu Wu"
date: "2023-09-17"
output: html_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r }
litters_df = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_df = janitor::clean_names(litters_df)
```
## `select`

Choose some columms and not others 

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)
```
You can specify the specify a range of columns to keep, gd_of_birth is the last column 
```{r}
select(litters_df, group:gd_of_birth)
```
You can also specify columns you’d like to remove:
```{r}
select(litters_df, -pups_survive)
```
You can rename variables as part of this process:
```{r}
select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
rename(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
```
helper functions for select 
```{r}
select(litters_df, starts_with("gd"))
select(litters_df, litter_number, pups_survive, everything())
relocate(litters_df, litter_number, pups_survive)
```

## `filter`

```{r}
filter(litters_df,gd0_weight<22 )
```

```{r}
filter(litters_df,gd0_weight>=22 )
```

```{r}
filter(litters_df,gd_of_birth==20 )
```

```{r}
filter(litters_df,gd_of_birth!=20 )
```

```{r}
filter(litters_df,gd0_weight>=22,gd_of_birth==20 )
```
group including either Con7 or Mod8 
```{r}
filter(litters_df,group %in% c("Con7","Mod8") )
```

mutate
```{r}
mutate(litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```
arrange
```{r}
head(arrange(litters_df, group, pups_born_alive), 10)
```
pipe %>% cmd+shift+m
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

litters_data
```

